### ISSUE TITLE
MJML visual editor adds ID tags which are now deemed as invalid

### ISSUE THREAD

**Issue by rafalsk** [mautic/mautic#10398]
### Mautic Version

4.0.0

### PHP version

7.4.19

### What browsers are you seeing the problem on?

Chrome

### What happened?

![image](https://user-images.githubusercontent.com/9338163/131669464-2fdf4790-eb37-47f3-a430-8cce9e9b656b.png)

now that's not a valid MJML.

### How can we reproduce this issue?

Step 1: like described above.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by adiux** [comment]
By default, I'm not getting the id on the mj-image tag. Can you please elaborate on how to reproduce?

**Comment by jonathandhn** [comment]
I've got this to happened. Invalid Id is added to images :        `<mj-image src="" id="iocri"/>`

|  Mautic | 4.0  |
|---|---|
| PHP | 7.4 |

This is the template I load :
```
<mjml>
  <mj-head>
    <mj-font name="Lato" href="https://fonts.googleapis.com/css2?family=Lato&display=swap" />
    <mj-font name="Roboto" href="https://fonts.googleapis.com/css?family=Roboto&display=swap" />
  </mj-head>
  <mj-body background-color="#fdfdfd">
    <mj-section background-color="#333333" background-url="https://theatre-oeuvre.com/wp-content/uploads/Bonne-mere-1-2048x695.png" background-size="cover">
      <mj-column>
        <mj-image src="https://mautic.theatre-oeuvre.com/media/images/grapesjs/logo_horizontal_tranparent_texte_noir.png" width="235px" alt="Logotype" />
      </mj-column>
    </mj-section>
    <mj-section background-color="#ffffff">
      <mj-column>
        <mj-text align="center" font-size="40px" font-family="Roboto, Consolas, Helvetica, sans-serif" font-weight="500">Insert text here
        </mj-text>
      </mj-column>
    </mj-section>
    <mj-section background-color="#ffffff">
      <mj-column>
        <mj-text font-family="Roboto, Consolas, Helvetica, sans-serif" align="center">Content 1
        </mj-text>
      </mj-column>
      <mj-column>
        <mj-text font-family="Roboto, Consolas, Helvetica, sans-serif" align="center">Content 2
        </mj-text>
      </mj-column>
    </mj-section>
    <mj-section background-url="https://mautic.theatre-oeuvre.com/media/images/grapesjs/logo_horizontal_tranparent_texte_noir.png" background-repeat="repeat" background-size="auto" background-color="#333333">
      <mj-column>
        <mj-text align="center" font-size="16px" font-weight="500" font-family="Lato, Arial, sans-serif" color="#ffffff" text-decoration="none" container-background-color="#333333">L'ŒUVRE | Association La Paix
          <br>1 Rue Mission de France
          <br>Belsunce - Marseille 13001 - FR
          <br>Cet email a été envoyé à {contactfield=email}
          <br>&nbsp;
          <br>&nbsp;
          <a href="{webview_url}" rel="noopener noreferrer" style="color: #ffffff; Text-Decoration: None;" target="_blank">Consulter en ligne</a> |
          <a href="{unsubscribe_url}" rel="noopener noreferrer" style="color:  #ffffff; Text-Decoration: None;" target="_blank">Désinscription</a>
        </mj-text>
        <mj-social icon-size="40%" border-radius="50%" mode="horizontal" container-background-color="#333333">
          <mj-social-element href="https://loeuvre.org" src="https://mautic.theatre-oeuvre.com/themes/toe_mjml/assets/web.png">
          </mj-social-element>
          <mj-social-element href="https://loeuvre.org/FB" src="https://mautic.theatre-oeuvre.com/themes/toe_mjml/assets/facebook.png">
          </mj-social-element>
          <mj-social-element href="https://loeuvre.org/IG" src="https://mautic.theatre-oeuvre.com/themes/toe_mjml/assets/instagram.png">
          </mj-social-element>
          <mj-social-element href="https://loeuvre.org/YT" src="https://mautic.theatre-oeuvre.com/themes/toe_mjml/assets/youtube.png" color="#000000">
          </mj-social-element>
        </mj-social>
        <mj-image src="https://theatre-oeuvre.com/wp-content/uploads/financeurs.jpg" width="600px" alt="Financeurs" />
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

This is the render once edited :
```
<mjml>
  <mj-head>
    <mj-font name="Lato" href="https://fonts.googleapis.com/css2?family=Lato&display=swap"/>
    <mj-font name="Roboto" href="https://fonts.googleapis.com/css?family=Roboto&display=swap"/>
  </mj-head>
  <mj-body background-color="#fdfdfd">
    <mj-section background-color="#333333" background-url="https://theatre-oeuvre.com/wp-content/uploads/Bonne-mere-1-2048x695.png" background-size="cover">
      <mj-column>
        <mj-image src="https://mautic.theatre-oeuvre.com/media/images/grapesjs/logo_horizontal_tranparent_texte_noir.png" width="235px" alt="Logotype"/>
      </mj-column>
    </mj-section>
    <mj-section background-color="#ffffff">
      <mj-column>
        <mj-text align="center" font-size="40px" font-family="Roboto, Consolas, Helvetica, sans-serif" font-weight="500">
          <p>Rendez-vous des b&eacute;n&eacute;voles
          </p>
        </mj-text>
        <mj-image src="https://mautic.theatre-oeuvre.com/media/images/201482783_2889054231412238_2258364037771609332_n.jpg" id="iocri"/>
        <mj-divider/>
        <mj-text>
          <p>
            <strong>Bonjour &agrave; tou.te.s,&nbsp;</strong>
          </p>
          <p>
            <strong>Vous &ecirc;tes b&eacute;n&eacute;vole&nbsp;&agrave; L&rsquo;&OElig;UVRE,<br />
              Vous avez &eacute;t&eacute;, ou souhaitez devenir b&eacute;n&eacute;vole,</strong>
          </p>
          <p>
            <strong>Rendez-vous le <span style="color:#e74c3c">jeudi 9 septembre 17h30-19h30</span> pour le rendez-vous&nbsp;de rentr&eacute;e !</strong>
          </p>
          <p>
            <strong>&Agrave; L&#39;&OElig;UVRE :&nbsp;1 rue Mission de France 13001</strong>
          </p>
          <p>
            <strong>On se retrouve pour organiser les &eacute;v&egrave;nements de la programmation, s&rsquo;inscrire sur les actions, s&rsquo;investir dans la vie du lieu, et bien s&ucirc;r se rencontrer et ap&eacute;roter !</strong>
          </p>
          <p>
            <strong>Chacun apporte quelque chose &agrave; boire, &agrave; manger, sal&eacute;, sucr&eacute;, &agrave; partager.</strong>
          </p>
          <p>
            <strong>&Agrave; jeudi !</strong>
          </p>
          <p>
            <strong>Bien amicalement,</strong>
          </p>
          <p>
            <strong>L&rsquo;&eacute;quipe de L&rsquo;&OElig;UVRE</strong>
          </p>
          <p>
            <strong>Bien &agrave; vous,</strong>
          </p>
        </mj-text>
        <mj-divider/>
        <mj-image src="https://mautic.theatre-oeuvre.com/media/images/img_3826.JPG" id="ijxsx"/>
      </mj-column>
    </mj-section>
    <mj-section background-color="#ffffff">
    </mj-section>
    <mj-section background-url="https://mautic.theatre-oeuvre.com/media/images/grapesjs/logo_horizontal_tranparent_texte_noir.png" background-repeat="repeat" background-size="auto" background-color="#333333">
      <mj-column>
        <mj-text align="center" font-size="16px" font-weight="500" font-family="Lato, Arial, sans-serif" color="#ffffff" text-decoration="none" container-background-color="#333333">L'ŒUVRE | Association La Paix
          <br>1 Rue Mission de France
          <br>Belsunce - Marseille 13001 - FR
          <br>Cet email a été envoyé à {contactfield=email}
          <br>&nbsp;
          <br>&nbsp;
          <a href="{webview_url}" rel="noopener noreferrer" style="color: #ffffff; Text-Decoration: None;" target="_blank">Consulter en ligne</a> |
          <a href="{unsubscribe_url}" rel="noopener noreferrer" style="color:  #ffffff; Text-Decoration: None;" target="_blank">Désinscription</a>
        </mj-text>
        <mj-social icon-size="40%" border-radius="50%" mode="horizontal" container-background-color="#333333">
          <mj-social-element href="https://loeuvre.org" src="https://mautic.theatre-oeuvre.com/themes/toe_mjml/assets/web.png">
          </mj-social-element>
          <mj-social-element href="https://loeuvre.org/FB" src="https://mautic.theatre-oeuvre.com/themes/toe_mjml/assets/facebook.png">
          </mj-social-element>
          <mj-social-element href="https://loeuvre.org/IG" src="https://mautic.theatre-oeuvre.com/themes/toe_mjml/assets/instagram.png">
          </mj-social-element>
          <mj-social-element href="https://loeuvre.org/YT" src="https://mautic.theatre-oeuvre.com/themes/toe_mjml/assets/youtube.png" color="#000000">
          </mj-social-element>
        </mj-social>
        <mj-image src="https://theatre-oeuvre.com/wp-content/uploads/financeurs.jpg" width="600px" alt="Financeurs"/>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

It can't be saved without code editing.

**Comment by adiux** [comment]
Can you please verify if the same thing happens in the GrapesJs MJML Demo https://grapesjs.com/demo-mjml.html

I was not able to reproduce it there:
![image](https://user-images.githubusercontent.com/13075514/131787300-ba4c9b2f-6407-4d91-bd60-c6e49346b554.png)

**Comment by jonathandhn** [comment]
OK goes to https://grapesjs.com/demo-mjml.html , then add an image at the top, I select "phone-app.png" from the demo library. 

output is : `<mj-image src="./img/phone-app.png" id="i6j59"/>`

linked to : https://github.com/artf/grapesjs-mjml/issues/179

**Comment by jos0405** [comment]
I can confirm it.
Steps to reproduce:
1. Open template (should be MJML)
2. Add image
3. Open code view, you won't see any id.
4. Upload any image, you'll see the id in the code view.
5. Saving impossible.

If you:
1. Open template (should be MJML)
2. Add image
3. Open code view, you won't see any id.
4. Upload any image, you'll see the id in the code view.
5. Delete id
5. Saving possible!

https://www.loom.com/share/952c72e046834a139883a8bd67f3ae60

**Comment by RCheesley** [comment]
This is resolved by #10462 which will ship with the 4.0.1 release. Thanks for reporting and testing everybody!

**Comment by RCheesley** [comment]
@all-contributors please add @rafalsk for bugs

**Comment by RCheesley** [comment]
@all-contributors please add @jonathandhn for bugs

**Comment by alexhammerschmied** [comment]
Should the ID issue be solved already? 
It is still happening in my environment.

**Comment by jonathandhn** [comment]
It's not resolved, tags are still hadded, but you are allowed to save and send email even with those tags since the last release 4.0.1.

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by adiux** [comment]
@rafalsk Since this is not an issue with the Mautic implementation of Grapesjs, can we close this issue here?
The issue is discussed here: https://github.com/artf/grapesjs-mjml/issues/179

With the removal of the strict mode in [4.0.1](https://github.com/mautic/mautic/pull/10462) we have a workaround for the time being.
