### ISSUE TITLE
Segment filters UI breaks on multiple edits

### ISSUE THREAD

**Issue by mabumusa1** [mautic/mautic#11430]
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

Changing filters of segments will be lost in case there is an error in one of the filters.

### How can we reproduce this issue?

This video shows the story behind the issue
https://www.loom.com/share/5207f6146c0f4721b9a2b1ae9b2eaaf8

Steps:

1. Create filters 
2. Edit them on the same session
3. Have an error in one of the filters
4. Your changes are lost

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
@julienWebmecanik maybe you have a fix for this right ?

**Comment by julienWebmecanik** [comment]
Highly possible that my fix resolves this too. We should test for confirmation

**Comment by julienWebmecanik** [comment]
should be fixed by https://github.com/mautic/mautic/pull/11434

**Comment by kuzmany** [comment]
👑

**Comment by PierreAmmeloot** [comment]
I have the same bug on Mautic v4.4.1.
I have test #11434 it's not working on my side (after clear:cache and m:a:g).

**Comment by jos0405** [comment]
Can you plz share your test in the PR @PierreAmmeloot ? We need to move forward with this fix. It worked for me, but it could be that I missed something.

**Comment by PierreAmmeloot** [comment]
@jos0405 I tested with the code of the PR and I see that the problem explained in this issue is still present on a Mautic instance on my side. How would you like to have more details?
