### ISSUE TITLE
500 error when downloading an asset

### ISSUE THREAD

**Issue by trevorhutt** [mautic/mautic#117]
The download asset had been working until this morning. 

I get a 500 internal server error when downloading the following asset (or any other asset).

http://avtech.mautic.com/p/asset/5:yellowfin-introductory-brochure

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@avtech.mautic.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by alanhartless** [comment]
Hey Trevor,

Can you look at app/logs/mautic_prod.php to see if any exceptions were caught related to that? If not, check your site's error log (varies by host) to see if a Php fatal error occurred. Post the error(s) here.

Thanks!
Alan

**Comment by trevorhutt** [comment]
The installation is hosted on your servers.  Can I access these logs?  I
seem to be having a number of issues, including a bug that generated 1170
leads all from my IP address.  The form redirections don't work, and I get
a error page when I try to use the message option when a form is submitted.
Another error I'm getting is that I can't delete the Adam Horan lead, or
the lead before it in the list.  I know that there was an issue with the
original provisioning of the site.  are these issue normal since the role
out?  Or should we just delete this install and reprovision a new one?

Regards

Trevor

**Comment by trevorhutt** [comment]
HI Alan,

I checked out my other install trevorhutt.mautic.com.  I set it up before
the upgrade and it seems to have upgraded ok and I'm not having the
problems that I am with the avtech.mautic.com site.  Can you please delete
the avtech.mautic.com and let me know when you've done so.  I am assuming
that if I set up a new site that it will be a clean install on yours
servers and hopefully the issues I have been having will be resolved.

Regards

Trevor

**Comment by alanhartless** [comment]
Hey Trevor,

I apologize.  I didn't realize you were using the hosted version. I looked at the logs and the errors you have encountered have been fixed in the source here and we'll be getting the fixes updated to the hosted sites this week. Once we reach the stable milestone, bugs found will be patched much quicker for hosted sites.

Thanks,
Alan

**Comment by trevorhutt** [comment]
Hi Alan,

Thanks for addressing the issues.  I'm hoping to release Mautic to our
Sales and Marketing team this week.  Then I can get onto some education
material for them (they're all gen-Y's who live in social media but they
seem to have no idea how online marketing works).  I will share it with you
guy's if you think it will be of use.

Regards

Trevor

**Comment by trevorhutt** [comment]
How did you go with rolling out the fix?

**Comment by alanhartless** [comment]
Hey Trevor!

I apologize.  Hosted accounts were updated late Sunday night with the latest code.  

Thanks!
Alan

**Comment by trevorhutt** [comment]
I setup another account avtechmarketing.mautic.com in the hope that I could launch this week.  However I still get a 500 error when submitting forms.

**Comment by alanhartless** [comment]
Hi Trevor,

Hi Trevor,

Can you give it another shot? New updates were rolled out a few hours ago and based on what I'm seeing in the log, the issue should now be resolved.

Also, going forward, please use the the Report a Bug link in the dashboard for hosted account issues. Github is going to be used for the community downloadable edition.

Thanks!
Alan
