### ISSUE TITLE
Send email twice!

### ISSUE THREAD

**Issue by dpopazov** [mautic/mautic#11763]
### Mautic Version

4.2.x series (not supported)

### PHP version

7.4.28

### What happened?

Mautic sends email twice to some contacts;

Condition:
We send emails for several segments. Contacts can be only in one of these segments but some (not all) of them received the same email twice.
We don't have duplicated contacts and duplicated segments.
Also I've checked mautics database and found out that mautic actually sends email twice to the same user with the same `email_id` (email) and with the same `list_id` (segment);

Screenshot from table `email_stats`;
![mautic_db](https://user-images.githubusercontent.com/74531954/204794969-c0acb615-5a69-468b-bfb9-c14d293106bf.png)

### How can we reproduce this issue?

Step 1: Create a batch of contacts;
Step 2: Create several segments and attach contacts to this segments in such a way the contacts shouldn't be duplicated between the segments (e.g. Contact A in Segment A, Contact B in Segment B);
Step 3: Create a new segment email and select  this segments;
Step 4: Publish email;

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, thanks for reporting this.

Please share the exact segment configurations you have so that we can attempt to reproduce this - I haven't experienced it myself having done a lot of testing.

We're currently on 4.4.5 so you are pretty behind the times if you are running 4.2.x which is unsupported. There have been around 10 bug fixes per release since then, so maybe 80-100 issues have been resolved if you're on an earlier version.

If it's only happening with a few contacts, it would suggest that there's some kind of configuration issue happening, perhaps, but we'd need more insights into your setup to confirm that. Maybe try with a blank Mautic instance to reproduce it (use https://gitpod.io/#https://github.com/mautic/mautic/ to do that, username admin password mautic).

**Comment by dpopazov** [comment]
> Hi there, thanks for reporting this.
> 
> Please share the exact segment configurations you have so that we can attempt to reproduce this - I haven't experienced it myself having done a lot of testing.
> 
> We're currently on 4.4.5 so you are pretty behind the times if you are running 4.2.x which is unsupported. There have been around 10 bug fixes per release since then, so maybe 80-100 issues have been resolved if you're on an earlier version.
> 
> If it's only happening with a few contacts, it would suggest that there's some kind of configuration issue happening, perhaps, but we'd need more insights into your setup to confirm that. Maybe try with a blank Mautic instance to reproduce it (use https://gitpod.io/#https://github.com/mautic/mautic/ to do that, username admin password mautic).

We've updated mautic to version 4.4.5 and bug still present.
I've tried to reproduce the similar behaviour on gitpod but I couldn't reproduce this bug.
Also I've made an investigation and found out that about 20k of our 100k subscribers (appr. 1/5) get duplicated emails. We don't have so large contact set for testing purposes. Probably so many contacts can cause duplication but I can't check that.

**Comment by exsesx** [comment]
@RCheesley I'm a team lead on a project with @dpopazov.

We've discovered what the issue was. Our marketing clicked "send" and also published the emails. So, the "send" finished processing some emails, and by the time the CRON task starts, emails that are left get triggered two times by the send and by the CRON task that picks up not yet sent emails. I hope that makes sense.

So, this issue can be closed. We believe there is no bug.

**Comment by RCheesley** [comment]
OK great - thanks for getting back to us @exsesx!
