### ISSUE TITLE
The landing page builder is missing preference center options when it is enabled

### ISSUE THREAD

**Issue by zeretrelle** [mautic/mautic#12103]
### Mautic Version

4.4.x series

### PHP version

7.4.33

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Enabling "Set as preference center page" doesn't add any preference blocks to the landing page builder. 

This  option sets the page as a preference page (you can selet it later on when creating an email), but the landing page builder doesn't have any blocks available to actually customize the preference page.

Here is the [short video](https://vmbekhterev-my.sharepoint.com/:v:/g/personal/organizator_teams_bekhterev_online/EdkzNBHdGh9OikS0vTvuPyQB-JUnrGVLo-ILyN04cdel7w?e=hfSH8K)

It looks like the issue is [6 months old](https://forum.mautic.org/t/preference-page-option-in-landing-pages-dont-show-up/25372/3)

### How can we reproduce this issue?

Step 1: create a new landing page
Step 2: enable "Set as preference center page" and save the page
Step 3: Click on "Builder"

### Relevant log output

```shell
No errors.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Hello @zeretrelle ! I'd suggest you to test https://github.com/mautic/mautic/pull/10579

**Comment by jos0405** [comment]
Solution is there, plz test and your problem is solved once migrated.

**Comment by zeretrelle** [comment]
> Solution is there, plz test and your problem is solved once migrated.

The bug is not fixed in the stable branch for production, so I gotta ask.. I'm sorry, but why is this closed?

**Comment by davidhealey** [comment]
This bug still seems to be present.

**Comment by introfini** [comment]
I confirm that the bug is still present in Mautic version 6 as well.

**Comment by leandroramos** [comment]
Same here.
