### ISSUE TITLE
When deleting a theme the confirmation modal is not readable

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#14559]
### Mautic Series

6.0.x series

### Mautic installed version

6.0

### Way of installing

I cloned the Mautic repo (not recommended or supported)

### PHP version

8.3

### What happened?

![Image](https://github.com/user-attachments/assets/97d66a3a-0ca8-45c0-8bc4-4a6d3e1fd907)

### How can we reproduce this issue?

1. Go to the theme listing
2. Click on the context menu for a theme
3. Select hide or show based on the state of the theme now.
4. This modal confirmation will show up.

### Relevant log output

```shell

```

### Code of Conduct

- [x] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by andersonjeccel** [comment]
@escopecz Dark mode?

**Comment by escopecz** [comment]
Yes, of course 🙂

**Comment by VishnuGurrapu** [comment]
@escopecz  is this issue is resolved

**Comment by escopecz** [comment]
@VishnuGurrapu do you have a link?

**Comment by VishnuGurrapu** [comment]
I initially wanted to work on this issue, but I didn't encounter the problem as described above. However, since the issue is still open, I wanted to check for any updates.

![Image](https://github.com/user-attachments/assets/35f40f6c-7683-4899-9cb1-adb33424b003)
![Image](https://github.com/user-attachments/assets/cf76f259-c181-42a0-9c63-54ac95dd2121)

**Comment by escopecz** [comment]
Aha! That was a question, not a statement. Got it.

I can still see the issue with the Dark theme set in my profile:

![Image](https://github.com/user-attachments/assets/1bb3a68c-2bc7-4fbd-9f54-e352d5523197)

As well as with the Freire theme:

![Image](https://github.com/user-attachments/assets/f032a1e4-1e35-4154-a5a4-518ff6060059)

Tested on the latest 5.2 as well as 6.x branches.

**Comment by VishnuGurrapu** [comment]
I understand it now. I have already worked on this issue and nearly completed it. Could you please assign it to me? I will raise a PR soon.

**Comment by VishnuGurrapu** [comment]
@escopecz, could you please review my PR?

**Comment by VishnuGurrapu** [comment]
@escopecz, could you please review my PR?
