### ISSUE TITLE
Hubspot integration plugin - pull contacts - existing contacts not updated

### ISSUE THREAD

**Issue by RDNSid** [mautic/mautic#4626]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | YES
| Feature request? | no
| Enhancement? | no

## Description: 
Using Hubspot integration plugin under v2.9.2, direction "pull from integration"
New Hubspot contacts are correctly populated in Mautic
Existing (=email) Mautic contacts are not updated from Hubspot : all integration fields are left blank

Checked and working : 
Plugin authentication with Hubspot API key + plugin published : OK
Enabled : pull contacts from integration
Choose what Hubspot Objects to pull data from : contacts
Contact mapping : OK
Cronjob OK

Maybe a side effect of #4368 ?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.9.2
| PHP version | 7.0.11

### Steps to reproduce:
1. Create new contact in Hubspot, populate core & custom fields
2. Modify existing contact in Hubspot that also exists (with same email) in Mautic
3. Run cronjob mautic:integration:fetchleads --integration=Hubspot
Cronjob OK (see output below) : 
`Command to fetch contacts from integration
Fetch contacts command is starting
Fetching contacts...
121 contacts were updated and 1 contacts were created
`

4. Check in Mautic : new contact OK, existing contact not modified, custom fiels zeroed out. 

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

Since v2.9.2, errors logged for **all** Mautic custom fields, even if custom field is published. Exemple : 
`[2017-08-08 16:20:18] mautic.NOTICE: PHP Notice - Undefined index: zohosubprice - in file /var/www/xxx/app/bundles/LeadBundle/Entity/CustomFieldRepositoryTrait.php - at line 302 [] []
[2017-08-08 16:20:18] mautic.NOTICE: PHP Notice - Undefined index: [customfieldname] - in file `

No other errors showing in logs. 

Will be happy to provide more specifics. 
Best regards, 
Pierre

**Comment by sineau** [comment]
Hello,
I faced the same issue but I didn't receive this notice (unless for a number of fields I deleted). In my case, the `mautic:integration:fetchleads` returns no error, but also the changes I made in Hubspot are not reflected in Mautic.

**Comment by franciscojun** [comment]
Same problem here. Fields are not retrieved from Hubspot (no error is displayed or logged).

**Comment by franciscojun** [comment]
In my case (Mautic v2.11.0), after a few code tweaks, I realized this is caused by an issue here: [https://github.com/mautic/mautic/blob/master/plugins/MauticCrmBundle/Integration/CrmAbstractIntegration.php#L405](https://github.com/mautic/mautic/blob/master/plugins/MauticCrmBundle/Integration/CrmAbstractIntegration.php#L405)

It turns out that $leadFields is set here (https://github.com/mautic/mautic/blob/master/plugins/MauticCrmBundle/Integration/CrmAbstractIntegration.php#L397) as a multi-dimensional array, like:
```
Array
(
    [objects] => Array
        (
            [0] => contacts
        )

    [update_mautic] => Array
        (
            [email] => 1
            [city] => 0
            [country] => 0
            [hs_facebookid] => 1
            [firstname] => 1
            [hs_googleplusid] => 1
            [lastname] => 1
            [hs_linkedinid] => 1
            ...
        )

    [leadFields] => Array
        (
            [email] => email
            [city] => city
            [country] => country
            [hs_facebookid] => facebook
            [firstname] => firstname
            [hs_googleplusid] => googleplus
            [lastname] => lastname
            [hs_linkedinid] => linkedin
            ...
        )

    [companyFields] => Array
        (
        )

)
```

But apparently this is not the expected input here (https://github.com/mautic/mautic/blob/master/plugins/MauticCrmBundle/Integration/CrmAbstractIntegration.php#L405):
```
$fieldsToUpdateInMautic = array_intersect_key($leadFields, $fieldsToUpdateInMautic);
```

$fieldsToUpdateInMautic doesn't have the expected format, too.:
```
Array
(
    [0] => email
    [1] => hs_facebookid
    [2] => firstname
    [3] => hs_googleplusid
    [4] => lastname
    [5] => hs_linkedinid
    ...
)

```

As a workaround (and because I'm not using any other CRM integrations, only Hubspot), I changed this line to:
```
$fieldsToUpdateInMautic = array_intersect_key($leadFields['leadFields'], array_flip($fieldsToUpdateInMautic));
```

Probably this has side effects on other CRM integrations, so, don't consider this as a permanent fix.

**Comment by PatteJun** [comment]
@franciscojun Thank you very much! Worked for me.

**Comment by afonseca08** [comment]
I can confirm this issue as well on a new Mautic 2.12.1 install I am just configuring. On sync with Hubspot running the cron job manually from the command line, I am able to get the contacts with the mapped fields to come across into Mautic. However, any field updates to a contact in Hubspot on subsequent run of the cron job do not update the contact in Mautic. This is definitely not working.

Since I need this functionality to work, I tried the change shared by @franciscojun and this fixed it for me as well.

@franciscojun, will you be making a pull request with the change so it gets into a future release?

**Comment by franciscojun** [comment]
Hi @afonseca08,

Glad to hear this workaround was useful to you.

Unfortunately it can't be considered a permanent fix, because it potentially breaks the compatibility with other CRM integrations. That's very likely, since the current code is supposed to be properly working with CRMs other than Hubspot.

I don't have the required time and CRM accounts to properly address this issue permanently, so, hopefully the devs managing this thread will be able to do so in a near future, so we don't need to edit the source code manually!

Thanks.

**Comment by afonseca08** [comment]
Just a quick update, this is still an issue with 2.13.1. I am continuing to use this workaround but would like to see this addressed in an upcoming release.

**Comment by SmittyTan** [comment]
Hi Guys - I have slightly different issue. It kept saying, hubspot error, you have reached your daily limit. According to hubspot 40,000 api request is allowed.  My cron job is running every half an hour so it should only be 48 calls in a day. Can anyone tell me what do I wrong?

**Comment by YahiaBakour** [comment]
Hey guys,

Is there a similar work around for updating company data ?

**Comment by afonseca08** [comment]
After updating to Mautic 2.15.0 I found the workaround is broken. Following the line of thinking introduced by @franciscojun I printed some debug output and found the $leadFields array now looks like this:
`Array
(
    [email] => email
    [firstname] => firstname
    [lastname] => lastname
    [claimed] => claimed
    [company] => company
    [exam_month] => exam_month
    [exam_year] => exam_year
    [first_time] => first_time
    [graduation_month] => graduation_month
    [graduation_year] => graduation_year
    [lead_source] => lead_source
    [hs_lead_status] => lead_status
    [license] => license
    [school] => school
    [winner] => winner
)`

So the relevant line (https://github.com/mautic/mautic/blob/master/plugins/MauticCrmBundle/Integration/CrmAbstractIntegration.php#L435)  now changes to this:
`$fieldsToUpdateInMautic = array_intersect_key($leadFields['leadFields'], array_flip($fieldsToUpdateInMautic));`

I'm still hoping someone that knows more about this can figure a way to put this into the official codebase so we don't have to keep hacking this workaround into every update.

The last few folks to touch this file, @Enc3phale @alanhartless @kuzmany maybe have some ideas?

**Comment by YahiaBakour** [comment]
Hey I'm not sure if anyone is having the same issue as me but i found a quick fix,

If you're trying to get dates from hubspot into mautic, it'll cause an error because hubspot sends the dates as 13 digit epoch times (When you choose the date picker option in hubspot). The code already existing code in mautic didn't work for me so i edited it to the following and it solved it. 

so you can fix it by changing the following lines (325 - 341): https://github.com/mautic/mautic/blob/6d201acec18815ba274130e9ad8d34d1ae3bf5ce/plugins/MauticCrmBundle/Integration/CrmAbstractIntegration.php#L325-L341

to the following:
```
      foreach ($matchedFields as $companyField => $value) {
            if (isset($companyFieldTypes[$companyField]['type'])) {
                switch ($companyFieldTypes[$companyField]['type']) {
                    case 'text':
                        $matchedFields[$companyField] = substr($value, 0, 255);
                        break;
                    case 'date':
                        $date                         = new \DateTime();
                        $date->setTimestamp((int)$value/1000);
                        $matchedFields[$companyField] = $date->format('Y-m-d');
                        break;
                    case 'datetime':
                        $date                         = new \DateTime();
                        $date->setTimestamp((int)$value/1000);
                        $matchedFields[$companyField] = $date->format('Y-m-d H:i:s');
                        break;
                }
            }
        }
```
if this helps anyone then yay!

**Comment by YahiaBakour** [comment]
Hey guys, I'm not sure if anyone is having the same issue as me but i seem to have found a quick fix for it.

If you're trying to import dates from hubspot (when you choose the date picker option) into mautic, it'll cause an error because it'll show an invalid date type. (I don't know if anyone else has the issue but here's how i fixed it anyways).

You need to change the following lines of code from 
https://github.com/mautic/mautic/blob/6d201acec18815ba274130e9ad8d34d1ae3bf5ce/plugins/MauticCrmBundle/Integration/CrmAbstractIntegration.php#L325-L341

to the following 

```
        foreach ($matchedFields as $companyField => $value) {
            if (isset($companyFieldTypes[$companyField]['type'])) {
                switch ($companyFieldTypes[$companyField]['type']) {
                    case 'text':
                        $matchedFields[$companyField] = substr($value, 0, 255);
                        break;
                    case 'date':
                        $date                         = new \DateTime();
                        $date->setTimestamp((int)$value/1000);
                        $matchedFields[$companyField] = $date->format('Y-m-d');
                        break;
                    case 'datetime':
                        $date                         = new \DateTime();
                        $date->setTimestamp((int)$value/1000);
                        $matchedFields[$companyField] = $date->format('Y-m-d H:i:s');
                        break;
                }
            }
        }
```

if this helped you then yay !

Warning: might break integration with other CRMs such as zoho or whatever, but if you're only using hubspot then this is for you !

**Comment by djmonzyk** [comment]
I applied the suggested fix in https://github.com/mautic/mautic/issues/4626#issuecomment-450332944 for v2.15.0 but I'm still not seeing anything update when I do a fetchleads console command.

**Comment by Muvuk** [comment]
hi, there, 

Am I missed something, or there is no way to keep synced mautic stage with hubspot lifecycle stage? 

Interesting thing add new contact from hubspot to mautic with right (lifecycle) stage works out of the box without mapped field! (after I created the same stages in mautic which already exist in hubspot.)

Is there a way to keep synced these data? 

thank you 

ps: I have tried both fixed from this issue, none of them worked me :(

**Comment by djmonzyk** [comment]
So, does anyone successfully have contacts updating from Hubspot -> Mautic in 2.15.0?  I'm ok with it being hardcoded right now, but I'm not seeing the identified fixes working for me, or it sounds like @Muvuk here, either....

**Comment by afonseca08** [comment]
@djmonzyk I have contacts updating from Hubspot to Mautic in 2.15.0 using the modified fix I posted earlier. However, the issue @Muvuk reports might be a different one as I noticed earlier that lifecycle stages didn't sync prior to 2.15.0 so I'm just not using them.

**Comment by djmonzyk** [comment]
@afonseca08 - You are so right, sorry. My code had reverted back to original during some server restoring I did and the change was lost.  I retried your code suggestion for 2.15.0 and just successfully tested a sync from Hubspot -> Mautic.  I also am not currently using lifecycle stages, but could see wanting to do so in the future.

**Comment by afonseca08** [comment]
Do we have someone from the community familiar enough with the Hubspot plugin to be able to integrate the appropriate fix for this issue? I'm concerned the code will diverge to the point where we won't be able to duct-tape it back to functioning in upcoming releases without help.

Tagging the contributors to HubspotApi.php to broaden the conversation: @gpassarelli @alanhartless @mqueme

**Comment by rikuto-bigarms** [comment]
As of v2.15.1, I can still confirm that this has not been resolved. Once a contact is pulled from Hubspot, it is no longer updated -- making recycle nurturing impossible. The fix will boost the value of integration 100 times... @alanhartless

**Comment by afonseca08** [comment]
I can confirm this is still an issue in 2.15.2.

**Comment by julienmarie** [comment]
Same here.

**Comment by dsecareanu** [comment]
Yes, still an issue in 2.15.2, any fix planned soon? 
I have tried the above suggested fix from @afonseca08 but didn't work for me.
This is killing the entire scope of this integration...

**Comment by billybobilly** [comment]
Having a similar issue.  Error:

[2019-09-16 11:05:39] mautic.NOTICE: PHP Notice - Undefined index: contacts - in file /var/www/mautic/app/bundles/PluginBundle/Integration/AbstractIntegration.php - at line 1853 {"lead":"[object] (Mautic\\LeadBundle\\Entity\\Lead: Mautic\\LeadBundle\\Entity\\Lead with ID #56)","config":{"leadFields":{"email":"email","firstname":"firstname","lastname":"lastname","city":"city","country":"country","company":"company","fax":"fax","mobilephone":"mobile","phone":"phone","zip":"zipcode","salutation":"title","address":"address1","website":"website"},"object":"contacts","feature_settings":{"objects":[]}},"fields":{"id":56,"title":null,"firstname":null,"lastname":null,"company":null,"position":null,"email":"info@xxx.com","mobile":null,"phone":null,"points":0,"fax":null,"address1":null,"address2":null,"city":"Chicago","state":"Illinois","zipcode":null,"country":"United States","preferred_locale":null,"timezone":null,"attribution_date":null,"attribution":null,"website":null,"last_active":null,"facebook":null,"foursquare":null,"googleplus":null,"instagram":null,"linkedin":null,"skype":null,"twitter":null},"leadId":56,"object":"contacts","leadFields":{"email":"email","firstname":"firstname","lastname":"lastname","city":"city","country":"country","company":"company","fax":"fax","mobilephone":"mobile","phone":"phone","zip":"zipcode","salutation":"title","address":"address1","website":"website"},"availableFields":[],"this":"[object] (MauticPlugin\\MauticCrmBundle\\Integration\\HubspotIntegration: {})"} []

[2019-09-16 11:05:39] mautic.WARNING: PHP Warning - Invalid argument supplied for foreach() - in file /var/www/mautic/app/bundles/PluginBundle/Integration/AbstractIntegration.php - at line 1861 {"lead":"[object] (Mautic\\LeadBundle\\Entity\\Lead: Mautic\\LeadBundle\\Entity\\Lead with ID #56)","config":{"leadFields":{"email":"email","firstname":"firstname","lastname":"lastname","city":"city","country":"country","company":"company","fax":"fax","mobilephone":"mobile","phone":"phone","zip":"zipcode","salutation":"title","address":"address1","website":"website"},"object":"contacts","feature_settings":{"objects":[]}},"fields":{"id":56,"title":null,"firstname":null,"lastname":null,"company":null,"position":null,"email":"info@xxx.com","mobile":null,"phone":null,"points":0,"fax":null,"address1":null,"address2":null,"city":"Chicago","state":"Illinois","zipcode":null,"country":"United States","preferred_locale":null,"timezone":null,"attribution_date":null,"attribution":null,"website":null,"last_active":null,"facebook":null,"foursquare":null,"googleplus":null,"instagram":null,"linkedin":null,"skype":null,"twitter":null},"leadId":56,"object":"contacts","leadFields":{"email":"email","firstname":"firstname","lastname":"lastname","city":"city","country":"country","company":"company","fax":"fax","mobilephone":"mobile","phone":"phone","zip":"zipcode","salutation":"title","address":"address1","website":"website"},"availableFields":null,"unknown":"Unknown","matched":[],"this":"[object] (MauticPlugin\\MauticCrmBundle\\Integration\\HubspotIntegration: {})"} []

**Comment by billybobilly** [comment]
Fixed. 
It turned out that if you don't have at least a first name defined, it will crash hubspot integration.  Adding a first name mapped field cleared the issue.

**Comment by dsecareanu** [comment]
I have the firstname mapped field and still I run into this issue of the Hubspot integration not syncronizing all Hubspot contacts nor any changes dones in Hubspot after the first contact sync.

**Comment by billybobilly** [comment]
> I have the firstname mapped field and I still run into this issue of the Hubspot integration not syncronizing all Hubspot contacts nor any changes done in Hubspot after the first contact sync.

I'm convinced these integrations have not been thoroughly tested for all use cases.  My problem was with the first sync and that was resolved with the mapping issue.  I'll test updates in HubSpot and give feedback.

**Comment by vexersa** [comment]
Hey guys, 
Same/similar issue where upon saving the Hubspot dialogue in Mautic, nothing happens and I'm left with a "Loading..." message infinitely. Related, perhaps?

**Comment by autoize** [comment]
> After updating to Mautic 2.15.0 I found the workaround is broken. Following the line of thinking introduced by @franciscojun I printed some debug output and found the $leadFields array now looks like this:
> `Array ( [email] => email [firstname] => firstname [lastname] => lastname [claimed] => claimed [company] => company [exam_month] => exam_month [exam_year] => exam_year [first_time] => first_time [graduation_month] => graduation_month [graduation_year] => graduation_year [lead_source] => lead_source [hs_lead_status] => lead_status [license] => license [school] => school [winner] => winner )`
> 
> So the relevant line (https://github.com/mautic/mautic/blob/master/plugins/MauticCrmBundle/Integration/CrmAbstractIntegration.php#L435) now changes to this:
> `$fieldsToUpdateInMautic = array_intersect_key($leadFields, array_flip($fieldsToUpdateInMautic));`
> 
> I'm still hoping someone that knows more about this can figure a way to put this into the official codebase so we don't have to keep hacking this workaround into every update.
> 
> The last few folks to touch this file, @Enc3phale @alanhartless @kuzmany maybe have some ideas?

Was testing the Dynamics CRM and HubSpot CRM integrations today, and can confirm the above code edit allows fields updated on the Integration side, to sync back over to the corresponding Mautic contact (if the direction of sync is set Integration => Mautic).

Thanks for the tip @afonseca08. Can we have a dev review and merge this?

**Comment by afonseca08** [comment]
Hi @autoize I just created a pull request with this specific change as it was back in 2017 that the first form of this workaround was introduced and it's 2020 today. I'll need someone to review it so it can be merged so any help would be appreciated!

[Fix field updates on sync from integration](https://github.com/mautic/mautic/pull/8278)

**Comment by mogalmahesh** [comment]
I tried the above fix mentioned by @afonseca08 . I am still facing issues with sync with Hubspot. I am using Mautic 2.16. Is there any other workaround for this?

**Comment by josecastano01** [comment]
> Hola, no estoy seguro de si alguien tiene el mismo problema que yo, pero encontré una solución rápida,
> 
> Si está tratando de obtener fechas de hubspot en mautic, causará un error porque hubspot envía las fechas como tiempos de época de 13 dígitos (cuando elige la opción de selector de fecha en hubspot). El código ya existente en mautic no funcionó para mí, así que lo edité a lo siguiente y lo resolvió.
> 
> para que pueda solucionarlo cambiando las siguientes líneas (325 - 341):
> 
> https://github.com/mautic/mautic/blob/6d201acec18815ba274130e9ad8d34d1ae3bf5ce/plugins/MauticCrmBundle/Integration/CrmAbstractIntegration.php#L325-L341
> 
> a lo siguiente:
> 
> ```
>       foreach ($matchedFields as $companyField => $value) {
>             if (isset($companyFieldTypes[$companyField]['type'])) {
>                 switch ($companyFieldTypes[$companyField]['type']) {
>                     case 'text':
>                         $matchedFields[$companyField] = substr($value, 0, 255);
>                         break;
>                     case 'date':
>                         $date                         = new \DateTime();
>                         $date->setTimestamp((int)$value/1000);
>                         $matchedFields[$companyField] = $date->format('Y-m-d');
>                         break;
>                     case 'datetime':
>                         $date                         = new \DateTime();
>                         $date->setTimestamp((int)$value/1000);
>                         $matchedFields[$companyField] = $date->format('Y-m-d H:i:s');
>                         break;
>                 }
>             }
>         }
> ```
> 
> si esto ayuda a alguien, ¡yay!


To this day I have this same problem.

I applied the suggested solution but the dates are wrong.

Do you have any solution for this?

Thank you,

**Comment by afonseca08** [comment]
Quick update, this is now fixed in 3.0.0-beta2.

**Comment by RCheesley** [comment]
Closing as fixed in Mautic 3.x
