### ISSUE TITLE
Mautic forms not submiting on mautic pages, show "please wait"

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#4652]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
In 2.9.1 and 2.9.2 forms are not submitting on my pages: you can view the page and put in info but when you submit it says "please wait". They work on other none-mautic pages when the html snippet is used. 

Here is an example http://ethical-pets.co.uk/m/uncategorized/becothings-competition-2 of one which is NOT working. If I embed the same form on a WordPress page it works fine.

I have checked and it is the case with new forms on new pages created just now (not clones), as well as pages I made / cloned before.

I spoke with johnwebmecanik on Mautic slack who helped me with it, but he could not replicate. It does not seem to be the same as : https://github.com/mautic/mautic/issues/4533 as I can see the page wether or not I am logged in and the "please wait" problem persists if I use it in a private window, or a totally different device. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.1 & 2.9.2
| PHP version | 

### Steps to reproduce:
1. Create form
2. Put on mautic page
3. Open page in private window
4. submit form
5. see "please wait" error
6. embed form code on basic html page or none mautic page (WordPress)
7. form submits okay
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by gingerling** [comment]
Here is the safe form in a WordPress page http://www.ethical-pets.co.uk/blog/win-becothings/ using manual copy: http://www.ethical-pets.co.uk/blog/win-becothings/

**Comment by YannickBiet** [comment]
is this the same form ?
it seems it redirects the user to another page when submitting in the second exemple while the firs tone try to display a message.

Can you share the form's successfull action config ?

**Comment by gingerling** [comment]
yes, same form. 

![screenshot from 2017-08-11 18-21-49](https://user-images.githubusercontent.com/2853040/29224504-9942d632-7ec2-11e7-88c2-c93759247d55.png)

![screenshot from 2017-08-11 18-22-39](https://user-images.githubusercontent.com/2853040/29224511-9cd6cc18-7ec2-11e7-8bac-9a6e16ca7c13.png)

Here is the config

![screenshot from 2017-08-11 18-26-59](https://user-images.githubusercontent.com/2853040/29224552-b88467e0-7ec2-11e7-8ad4-b4c67214839d.png)
![screenshot from 2017-08-11 18-27-03](https://user-images.githubusercontent.com/2853040/29224554-ba1441ca-7ec2-11e7-98be-3a4fed165609.png)

**Comment by AndrassGray** [comment]
Anna, have a look here. Stuck forms yesterday for two guys on Slack. Maybe this fixes your problem as well: https://github.com/mautic/mautic/pull/4656/files

**Comment by gingerling** [comment]
Hope so! Is that patch going to be released soon? I will probably wait if so, rather than go messing about with code

**Comment by gingerling** [comment]
Hi, I did the first change but not the second change - the code in my mautic-form-src.js form is not the same. There is a similar section to that mentioned on line 34 but it's on 561 for me, and those specific lines are not there. anyway, the one change has not fixed the issues.

It does seem like the data is being recorded right now.

However most concerning, someone reported this issue on one of my pages which was not a Mautic page.

This is really disrupting my ability to use mautic now, I am getting quite frustrated. Anyone to help?

**Comment by pavel-janicek** [comment]
Just pinging you. I applied patch already mentioned in https://github.com/mautic/mautic/pull/4656 and after that I cleared Mautic cache and from command line run php `path/to/mautic/console mautic:assets:generate` and this solved my problem.

So if you applied the patch, but did not run `mautic:assets:generate` command, please try that too

**Comment by gingerling** [comment]
Thanks for the ping, I will discuss this with my hosting company support team, it's a bit over my skill level 😊

**Comment by Schokolader** [comment]
Is this in the new mautic version included? Can I test it with mautic 2.10.0 ?

**Comment by khaoua** [comment]
on 2.10 and it's not working, I followed the instructions from this link below, update wp-plugin, tracking works, but forms shows "please wait" on submition, which was the case in previous version, any idea?

https://mautic.com/help/forms-hanging/

**Comment by RCheesley** [comment]
I think this needs the RTT label to be removed, as the original PR was closed by @escopecz and the issue persists in 2.12.0 (forms are being submitted, but redirect is not happening, due to the mautic instance being in a different location to the website the forms are located on).

**Comment by IADDIC** [comment]
The issue persistes in 2.12.1 as well.

**Comment by RCheesley** [comment]
Indeed, pretty fatal for several of our clients without any kind of workaround :| Would be helpful to know what the suggested route forward would be if the previously mentioned solution is not workable.

**Comment by ModPilot** [comment]
I'm dead in the water too.  Forms embedded in my wordpress site die with "Please Wait" (although the submission does go through... just never redirects or displays a message (tried both ways)).

**Comment by gingerling** [comment]
Hi, I don't have this issue with manually embedded forms - only with automatic. Not sure if that is the workaround that isn't working for you?

**Comment by escopecz** [comment]
I think/hope this will be fixed with https://github.com/mautic/mautic/pull/5558

**Comment by RCheesley** [comment]
Will give it a test and report back, thanks guys!

**Comment by alanhartless** [comment]
Fixed in 2.12.2 beta

**Comment by khaoua** [comment]
@alanhartless @dbhurley  I was doing this workaround described below on each updgrade (from 2.9.2 to 2.10 the bug occurred on my side)

Update in both /mautic-form-src.js and /mautic-form.js, the code [code]if (event.origin !== MauticDomain) return;[/code] is in both of them. (was search for "event.origin" in the files to find the lines to be changed)

Then replace [code]if (event.origin !== MauticDomain) return;[/code]

with

[code]var MauticDomainWithoutPath = MauticDomain.match(/https?://[^/]*/);
if (event.origin != MauticDomainWithoutPath) return;[/code]

it worked well for me as the solution was described here in github by "MichaelvanLaar", (files can be found in /media/js)

does that mean that in beta 2.12.2 this workaround is not necessary anymore? what if we already did that workaround and then move on 2.12.2 ? any risk or will it work? is it tested? I'm addressing it as this workaround is used by many community members (at least the ones knowing it)

**Comment by escopecz** [comment]
@khaoua see the PR I linked above (https://github.com/mautic/mautic/pull/5558). There is the code change that is in Mautic 2.12.2 so you can test it and see who also tested it.

**Comment by khaoua** [comment]
@escopecz did not have the chance to test it, is it sustainable now, as it seems @bogdankuts still have the issue

**Comment by escopecz** [comment]
@bogdankuts can you please provide a link to the page where the Mautic form does not work? It may be several reasons. CORS or URL mismatch. Some tips to try are described in the docs:

https://mautic.org/docs/en/forms/index.html#form-troubleshooting

**Comment by diogodaluz** [comment]
Escopecz. I Have the same: "Please wait" after submit form and the form isn´t redirect to success page.

Mautic v2.12.2 - PHP 7.1

Important: This problem is generated if the form is being used as a campaign source for some campaign.

If disable campaign the form works FINE redirecting to success page normally.

In both cases the data are registered.

**Comment by npracht** [comment]
On my side i can see the same issue.
Same as @diogodaluz it is a campaign form. But i tried while disabling the campaign and it is still not working.

**So it must have something related to campaign form.**

**Comment by diogodaluz** [comment]
@escopecz @npracht , Another important note: in form "preview" mode inside mautic dashboard it´s the same. Works fine without campaign and "Please wait" with campaign enabled.

**Comment by giovanner** [comment]
Any solution ?

**Comment by pavel-janicek** [comment]
Upgrading to 2.12.2 (or higher) worked for me. However, to make it fully workable, I needed to run these commands on server:
`php path/to/mautic/app/console mautic:assets:generate
 php path/to/mautic/app/console cache:clear`

In one instance, I had to generate the forms from the GUI. 

But when doing this, it works like treat

**Comment by nikhilthecool** [comment]
Upgraded to 2.14.2 yesterday and all Mautic Forms are now asking to "Please wait" on clicking the submit button. Totally frustrating..

First of all, while updating Mautic, all steps were completed except that it got stuck at "clearing application cache". I googled out on the forum and got the cache cleared using the command line. Mautic started working thereafter and I could see that it was upgraded to 2.14.2

However, later I observed that mautic forms were not getting submitted and were stuck at "Please Wait". I tried creating new forms also, but the same issue persisted in new forms as well.

I replaced the line: 
`if (event.origin !== MauticDomain) return; `
with
```
var MauticDomainWithoutPath = MauticDomain.match(/https?://[^/]*/);
if (event.origin != MauticDomainWithoutPath) return;
```
in both mautic-form-src.js and mautic-form.js but to no avail.

I also run the two commands thereafter, but still no progress.
` php path/to/mautic/app/console mautic:assets:generate`
`php path/to/mautic/app/console cache:clear`

Output of both the commands:
>  [OK] Cache for the "prod" environment (debug=false) was successfully cleared.
> Production assets have been regenerated.

Here are both the files.
[mautic-js_src.zip](https://github.com/mautic/mautic/files/2522494/mautic-js_src.zip)

I am now totally stuck up where none of my forms are working and l'm losing valueable business. I've started regretting my decision to use Mautic 👎 

Any help will be seriously appreciated.

**Comment by escopecz** [comment]
@nikhilthecool check out https://github.com/mautic/mautic/issues/6783 

That's the only form problem I know about on 2.14.2

**Comment by pavel-janicek** [comment]
@nikhilthecool In these cases it helped me a lot to rebuild cache of forms directly inside Mautic:
<img width="202" alt="forms___mautic" src="https://user-images.githubusercontent.com/13867730/47636642-5934b980-db59-11e8-9c4e-538590fbc2a8.png">

**Comment by fastflowapps** [comment]
This problem is still present in both 2.15 and 2.15.1

Replacing the the event.origin code did not work for 2.15

Instead removing both /mautic-form-src.js and /mautic-form.js files works for the form submit in 2.15 but this is not ideal is it will probably affect other mautic functions

Removing the files in 2.15.1 breaks the form submit with redirection to an error page

**Comment by ravinayag** [comment]
Hello,  I have encountered the same problem and did further research on this. 
1, my setup 2.14.1  upgraded to 2.15.1,  >>>>> No luck, the form still sucks with please wait.
2, Did a fresh install with 2.15.1  >>>>>>> NO ISSUE, All GOOD. 
3, Fresh install 2.15.1, and redirect the DB to 2.14.1 >>>>>>> No luck, the form still sucks with please wait.
which puts me to further do deep dive into the issue,  thought of related to Database issue so i redirect db (2.15.1) to 2.14.1 app.  Still no luck, the issue remains.

Concluded: Fresh install of 2.15.1 works well, But my question how to migrate ...?  i,e, take all my data like segments, email templates, forms, ......... and migrate to 2.15.1. .?????

**Comment by escopecz** [comment]
@ravinayag The Mautic upgrade process will do it for you. If there is some error along the way then check https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful

**Comment by virgilwashere** [comment]
@marcelloinfoweb do you still have issue?

WordPress site with embedded forms?

Is form a source for a campaign?

**Comment by garzettone** [comment]
I have the "Please wait" problem after update to v2.15.3 version.
Before update it was working.
This problem make Mautic unusable

**Comment by marcosjoao37** [comment]
I had that same problem. I wrote about it in another thread. I hope that could help: https://github.com/mautic/mautic/issues/4005#issuecomment-1955758962
