### ISSUE TITLE
Error after updating to Mautic 2.12.0

### ISSUE THREAD

**Issue by fonini** [mautic/mautic#5459]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
I've updated a 2.8 Mautic installation to 2.12.0. 
When I try to warm up the cache, I get the following error:

`[Doctrine\ORM\Mapping\MappingException]
  Duplicate definition of column 'id' on entity 'Mautic\CoreBundle\Entity\MessageQueue' in a field or discriminator column mapping.`

| Q   | A
| --- | ---
| Mautic version | 2.12.0
| PHP version | PHP 7.0.22

### Steps to reproduce:
1. ` php app/console cache:warmup --env=prod`

**Comment by Bizcrony** [comment]
how did you try to update?

**Comment by fonini** [comment]
Found the solution.

Turns out some files weren't deleted.
Removed the `Mautic\CoreBundle\Entity\MessageQueue.php` file and it worked.

Thanks.

**Comment by biplobice** [comment]
I faced same problem on 2.12.1
@fonini  Thanks for the tips. It works!
I think this should be fixed in core.

**Comment by djschoone** [comment]
solved it for us as well. thnx @fonini

**Comment by RCheesley** [comment]
Same problem, I did an update from 2.7.1 to 2.12.2 and I came up against this error when I tried to clear the cache after the update (following a system error on loading mautic).

Seems this is perhaps still missing from the migration scripts @escopecz but the bug remains - this issue has been closed?

**Comment by Bizcrony** [comment]
@RCheesley RCheesley May i try to upgrade for you.

**Comment by RCheesley** [comment]
I've already resolved the upgrade following the instructions, thanks for the kind offer @Bizcrony

**Comment by Bizcrony** [comment]
cheers
