### ISSUE TITLE
Bug : Fresh themes can not download !

### ISSUE THREAD

**Issue by kolinz** [mautic/mautic#5492]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? |  N
| Enhancement? | N

## Description:
Several themes can not download. Themes name are ....

- Fresh - Wide Form (fresh-wide)
- Fresh - Center Form (fresh-center)
- Fresh - Fixed Form (fresh-fixed)
- Fresh - Left Form (fresh-left)

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.12 and Mautic Cloud Free
| PHP version |  7.0.24

### Steps to reproduce:

1. go to Settings --> Themes
2. Check on the theme (Fresh - Wide Form ,  Fresh - Center Form, Fresh - Fixed Form, Fresh - Left Form)
3. Click "download"
4. Error Message

- Self hosting version Mautic 2.12 Error message：404 Not Found
- Mautic Cloud Free Error message：Lost by chance? I couldn't find the page you were looking for. May I suggest a search?

 
### Log errors: 

none

**Comment by npracht** [comment]
The alias does not support - character in its name. It should be renamed with an _ instead.

Envoyé de mon iPhone

**Comment by kolinz** [comment]
@npracht san
Thank you for you reply.

It was confirmed that alias does not support  - character . But, These themes are official theme and created by Mautic.  I think These themes need to make some modifications to the "config.json".

I got the theme file from the git  and changed the "config.json" as below. Themes file uploaded. it was solved. It's ok, _ or space .

mautic/themes/fresh-center/config.json
- now         "name": "Fresh - Center Form",
- changed   "name": "Fresh Center Form",
upload : fresh-center.zip

mautic/themes/fresh-fixed/config.json
- now         "name": "Fresh - Fixed Form",
- changed  "name": "Fresh Fixed Form",
upload : fresh-fixed.zip

mautic/themes/fresh-left/config.json
- now         "name": "Fresh - Left Form",
- changed  "name": "Fresh Left Form",
upload : fresh-left.zip

mautic/themes/fresh-wide/config.json
- now         "name": "Fresh - Wide Form",
- changed  "name": "Fresh Wide Form",
upload : fresh-wide.zip

**Comment by secure11** [comment]
This is still an issue in 2.13.1. I receive an error on all mautic-supplied themes and one custom theme I uploaded. When selecting the dropdown menu to the left of the theme name, and then Download, error in upper right corner "Theme {name here} not found" Happens with all themes.
