### ISSUE TITLE
Mautic removes `mautic:disable-tracking` attribute for links

### ISSUE THREAD

**Issue by LordMike** [mautic/mautic#7173]
## Bug Description

I was trying to use the `mautic:disable-tracking` for a specific link, but every time I saved my template, the attribute disappeared.

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.1.26
| Browser | FF 64.0.2

### Steps to reproduce
1. Create template with link
2. Add `mautic:disable-tracking` as an attribute
3. Save it
4. Observe the attribute is gone
 
### Log errors
N/A

### Code

I've tracked these two pieces of code I think are related.

* [parseContent](https://github.com/mautic/mautic/blob/839d619a7ff36a11b5683c6b8f0a7cd6086e3f5e/app/bundles/PageBundle/Model/TrackableModel.php#L884-L894) -- removes the attribute
* [extractTrackablesFromHtml](https://github.com/mautic/mautic/blob/839d619a7ff36a11b5683c6b8f0a7cd6086e3f5e/app/bundles/PageBundle/Model/TrackableModel.php#L385-L399) -- would have utilized the attribute to disable tracking for individual links. This code is called immediately after the building of the replacement table above

Also, isn't the `contentReplacements` array empty? .. The `first_pass` is set twice..

**Comment by ericgopak** [comment]
Sorry that this post is almost a year old, but have you tried replacing `mautic:disable-tracking` with `mautic:disable-tracking="true"`?

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
#7272 could maybe be related?

**Comment by dennisameling** [comment]
Can confirm this bug still exists in 3.0.2 while testing the feature for a customer. When switching to code view I add the `mautic:disable-tracking` attribute:

```HTML
<br><a href="https://google.nl" mautic:disable-tracking="true">https://google.nl</a>
```

When closing and re-opening code view the attribute is gone:

```HTML
<br><a href="https://google.nl">https://google.nl</a>
```

When I directly insert the attribute in the database column (`emails > custom_html`) the feature works as expected, so it's a frontend bug that strips out the attribute incorrectly.

**Comment by RCheesley** [comment]
@dennisameling @LordMike has this been resolved with the recent fixes to Froala or is it persisting?

**Comment by LordMike** [comment]
To be fair, I have not used Mautic for a year or two, due to other (internal) issues as well. I do not recall if this was resolved for us.

This issue can be closed for our sake.

**Comment by RCheesley** [comment]
@LordMike OK let's just check if it's still an issue as it was reproducible back in August - otherwise we'll close it. Thanks for getting back to us!

**Comment by pwned555** [comment]
I can confirm this is still an issue with v3.2.4 following the steps outlined by @dennisameling

From initial testing I believe we just need to add a htmlAllowedAttrs to the app\bundles\CoreBundle\Assets\js\11.editor.js
Line 17 has htmlAllowedAttrs: [...]
When 'mautic:disable-tracking' is added to that array and autogenerated media\js\app.js is deleted and updated it allows the tag as expected.

**Comment by npracht** [comment]
@pwned555 would you be okay carrying a Pull Request to the code base to solve the issue ?
Thanks a lot !!!

**Comment by npracht** [comment]
@pwned555 did you have the chance to have a look at this to offer a PR to the community ?
Thanks !
