### ISSUE TITLE
Mautic Update stuck on Moving package content

### ISSUE THREAD

**Issue by Pd08111997** [mautic/mautic#7762]
I am getting an error while updating mautic.

The update is stuck on moving content package.

What Should I do?

**Comment by gino1234** [comment]
Mine did that too... I tried then to do a manual update and everything broke. Luckily I had db backup and app directory backup.
During this whole attempted update I got lots of errors in the logs. I also noticed that in this update the .htaccess file has some directory permission changes - I’m not totally sure but the directives were for apache 2.4 - I’m still using 2.2 and so it was causing a authtype error ...

**Comment by jclimac** [comment]
I'm facing this issue as well.

Looking at Chrome's Devtools I see a call to the following address which returns a 404 not found.

https://my_mautic_url.com/upgrade/upgrade.php?task=moveBundles&updateState=W10=&_=1564956138124&mauticUserLastActive=3&mauticLastNotificationId=

And there is no upgrade.php at upgrade folder on the server.

Also, I'm not using Apache, I'm using Nginx.

**Comment by gino1234** [comment]
If you have your database backed up and any custom files too then I’d trash the installation and download the same version you were using and use that until this is resolved.

**Comment by jclimac** [comment]
Thanks @gino1234 , luckily in my case it's not necessary, the automatic update did not screw up the current installation (currently installed v2.15.2-beta). It just downloaded the new package and extracted it. The error comes right away the extract step and did nothing on the server, there is just a new "upgrade" folder.

**Comment by Ezyweb-uk** [comment]
Same issue here on Apache 2.4 upgrading from Mautic 2.14.0 via the dashboard.

**Comment by danwaterloo** [comment]
Same problem, I'm using php 5.6, and apache 2.2. got stuck, the only way to restore was to download a clean zipped version of 2.15.1, unzip, and restore the local.php in app/config folder. 
As an aside, I have yet to run the upgrade script from the web interface, and have it work properly. (Since 2016).  Mautic itself creates such slowness on my website that I have deactivated almost everything (which spead up my website conserderably).  Not too reassuring...

**Comment by directpromo** [comment]
Duplicate of #7758

**Comment by Ezyweb-uk** [comment]
@directpromo your fix in #7758 is to add the file access rules to .htaccess but I don't see how that would have any effect as the issue seems to be related to the upgrade.php. Also I'm running Apache 2.4 ( EasyApache4 - not 2.2). Anyway I tried it and no difference.

**Comment by directpromo** [comment]
> @directpromo your fix in #7758 is to add the file access rules to .htaccess but I don't see how that would have any effect as the issue seems to be related to the upgrade.php. Also I'm running Apache 2.4 ( EasyApache4 - not 2.2). Anyway I tried it and no difference.

What error messages do you see in the server logs?

**Comment by Ezyweb-uk** [comment]
@directpromo I see now what confused me, in your code.txt file it refered to update.php but this has since been changed to upgrade.php in the latest .htaccess code. In the Apache error_log file I found the error: '[authz_core:error] ... client denied by server configuration' so it does looks like the same issue as #7758

**Comment by directpromo** [comment]
> I've added those rules to the .htaccess in the root and to the .htaccess in the upgrade folder and re-run the update.

@Ezyweb-uk I tried that too. It did not help, because the distribution every time you try to update downloaded again and overwrites the files in the upgrade folder.

Either update completely manually or wait for the release with a fixed bug.

**Comment by tradenet** [comment]
FYI, this issue is also with Nginx installations.

**Comment by directpromo** [comment]
@tradenet 
@jclimac 
I created bug report for update error on nginx #7769

**Comment by dageci** [comment]
I also have this problem.

**Comment by Bannerman** [comment]
Same issue here.

**Comment by matheushirota** [comment]
Same issue here, i have more than 10 instances and all with the same issue

**Comment by drimlike** [comment]
Same issue on trying to upgrade from 2.14.0 to 2.15.2, anyone managed to get the upgrade working?

**Comment by Ezyweb-uk** [comment]
@drimlike yes I got a test installation update working today, but I had to temporarily change the update package url and self-host an updated version of update zip with the typo corrected in .htaccess - more info on https://github.com/mautic/mautic/issues/7758#issuecomment-521199380

**Comment by Bizcrony** [comment]
The best way to upgrade 


1.Login SSH 

2.Go to mautic root where mautic has installed like /var/www/html/Mautic/


3 For Clear cache run this command: php app/console cache:clear OR rm -rf app/cache
 
 
4.To check mautic latest version available RUN: php app/console mautic:update:find


5.To update Run: php app/console mautic:update:apply -- force


6.Try to run database migrations: php app/console doctrine:migration:migrate


7.Try to update database schema: php app/console doctrine:schema:update --force


8.Run to warm up cache: php app/console cache:warmup


9.To Give permission to cache folder: sudo chmod -R 777 /var/www/html/Mautic/app/cache


10.Clear your browser cache also and you will see your mautic has upgraded

**Comment by npracht** [comment]
@Bizcrony this is not about fixing manually the update. But insure the automatic update working properly. Can you technically dig into it and find the way to PR a solution?

**Comment by Ezyweb-uk** [comment]
All it needs is the .htaccess file in the release package updating with the version from the staging branch, I've simulated this and it worked (once I fixed a foreign key in the database) . But I understand we have to wait for a major release until this happens. Is there a possibility of a minor release on a shorter timescale?

**Comment by escopecz** [comment]
The community is working on 2.15.3 which will fix this regression. If you wish to upgrade, do so via CLI which is the preferred way how to upgrade Mautic: https://autoize.com/ensure-successful-mautic-upgrade/ or wait for 2.15.3.

**Comment by afonseca08** [comment]
I experienced the same issue coming from 2.13. The workaround using the command line worked for me. I believe the web interface will become the preferred way to upgrade once it works reliably.

**Comment by YosuCadilla** [comment]
Hi guys,

For me, upgrading from 2.15.2 to 2.15.3-beta was shown as succesful on the GUI, but didn't update my schema.
Updating from 2.15.3-beta to 2.15.3 failed to complete (in the last step).

So I decided to never use the "button again" and do all updates manually, which in my experience, works 100% of the time.

I've just uploaded a "Mautic Update How-To" with the steps I follow to my blog.

https://mauteam.org/mautic/mautic-admins/mautic-update-how-to-dont-click-that-button/

Hope it's useful!

**Comment by MimirRnD** [comment]
Sorry guys, but nothing of any of the suggestions work
It is still an issue in the DB for me.
I have held back from upgrading from 2.14 for 1.5 years.
It is a proper joke that no one has even bothered to get this right. The problem is an old problem 

Error I get is [Doctrine\DBAL\Schema\SchemaException]
  The table with name '<mautic database name>.customernominalledger' already exists.

**Comment by escopecz** [comment]
@MimirRnD what's in the customernominalledger table? It's not a Mautic table.

**Comment by MimirRnD** [comment]
> 
> 
> @MimirRnD what's in the customernominalledger table? It's not a Mautic table.

Do not know. It is installed by default so we have not made any changes to the DB

**Comment by MimirRnD** [comment]
Thanks a lot! Your comment made it. I deleted it. IT was the consultant who installed it one year ago that had added a table with that name

**Comment by escopecz** [comment]
What's the error now?

**Comment by MimirRnD** [comment]
The error is now:

The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.
System administrators, check server logs for errors.

**Comment by escopecz** [comment]
> check server logs for errors

Do this
