### ISSUE TITLE
Campaign comparison condition with a form field 'Number' is performed lexicographically

### ISSUE THREAD

**Issue by shimisnow** [mautic/mautic#7809]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

A campaign form  was created with a field type as Number. A campaign was created to make a decision using the form field as condition. If the the condition is true (green path), the contact is added to a segment. If the condition is false (red path), the contact is removed from a segment.

The condition compare the numeric field lexicographically rather than numerically. The result is that a comparison like 9 > 58000 is true.

**What was tested**

1. When the error was identified, another field was created. Then another form and then another campaign. None of these actions solved the problem.
2. The environment was a clean 2.15.2 installation with PHP 7.1 on Debian 9. Changing the PHP version to 7.0 had no effect.
3. A new Mautic 2.15.1 installation was made with PHP 7.0 and the same problem occurs.

**Additional information**

In the form results screen, sorting the Number field column, the result is also lexicographically sorted.

![erro-campaign-comparison-form](https://user-images.githubusercontent.com/14943507/63439652-d725c200-c404-11e9-95a9-09b01136df9e.jpg)

**Related issue**

[#5786 - Campaign - Comparison in a Condition for a form field value typed as "Number" is performed lexicographically ](https://github.com/mautic/mautic/issues/5786)

**Screenshots**

![erro-campaign-comparison-tree](https://user-images.githubusercontent.com/14943507/63439912-52877380-c405-11e9-95b6-f6bc061ea1b4.jpg)

![erro-campaign-comparison](https://user-images.githubusercontent.com/14943507/63439921-561afa80-c405-11e9-9ed5-6b39d0f2352b.jpg)

| Q   | A
| --- | ---
| Mautic version |  2.15.2 and 2.15.1
| PHP version | 7.1 and 7.0
| Browser | not apply

### Steps to reproduce

1. Create a form with a field type 'Number'
2. Submit the form with values as 56000, 9, 100, 78
3. Create a campaign and use the condition box selecting "form field value" in the dropdown
4. Select the created form
5. Set the field (created and defined as "Number")
6. Set the comparison operator as "greater than"
7. Set the value as 58000
8. Run the campaign
9. Submissions with the field value as 9 and 78 will follow the decision green path, resulting in 9 > 58000 = true and 78 > 58000 = true

### Log errors

- There is no error on Mautic Log
- There is no error on Server Log

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by shimisnow** [comment]
I was able to partially resolve the bug described by applying the changes of the Pull Request #7705 on Mautic 2.15.2 running with PHP 7.0

**Changes**

The three files listed in the Pull Request was modified with the exact code changes from the Pull Request

**What part was resolved**

The condition in a campaign comparing a numeric field lexicographically rather than numerically

**What part was not resolved**

In the form results screen, sorting the Number field column, the result is still lexicographically sorted.

**Comment by RCheesley** [comment]
This was resolved with #7705 and is a duplicate of #5786 so closing the issue :tada:

**Comment by oytuntez** [comment]
This issue still continues for other field types, such as "hidden". I think the comparison operator determines what type to cast the value to. If condition is `gte`, than then the value must be cast to numeric.

Broken SQL:
`select * from form_results_17_vendor_nps where grade >= '9';`

yields only those with grade = 9

Better SQL:
`select * from form_results_17_vendor_nps where grade >= 9;`
or
`select * from form_results_17_vendor_nps where grade >= CAST('9' AS UNSIGNED);`

yields those with grade = 9 and grade = 10.
