### ISSUE TITLE
Error in the Polish translation of the pagination

### ISSUE THREAD

**Issue by tomekkowalczyk** [mautic/mautic#9725]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When changing the language to Polish, pagination stops working in the user's profile

`[2021-02-16 09:12:01] mautic.ERROR: Symfony\Component\Translation\Exception\InvalidArgumentException: Unable to choose a translation for "one: %count% strona|some: %count% strony" with locale "pl_PL" for value "8801". Double check that this translation has the correct plural options (e.g. "There is one apple|There are %count% apples"). - in file /home/www/mautic.krakow.comarch/www/vendor/symfony/translation/MessageSelector.php - at line 89 [] []`

![image](https://user-images.githubusercontent.com/39382654/109009133-77ba0980-76ae-11eb-9f8f-c0efbb5a6545.png)

In the transifex system this translation looks correct. Anyone have an idea how to correct it? 

![image](https://user-images.githubusercontent.com/39382654/109007813-d7afb080-76ac-11eb-911a-fdd34acc13e7.png)

![image](https://user-images.githubusercontent.com/39382654/109008191-51479e80-76ad-11eb-899b-8895e04f674c.png)

| Q   | A
| --- | ---
| Mautic version | 3.2.4
| PHP version | 7.3
| Browser | 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by directpromo** [comment]
The error has been repeated for a long time and repeatedly
https://github.com/mautic/mautic/issues/8716

It seems to be a problem with different languages.

**Comment by directpromo** [comment]
@tomekkowalczyk check your other bug. It can be linked
https://github.com/mautic/mautic/issues/8719

**Comment by RCheesley** [comment]
Thanks for reporting this, it looks like the translation string in use:

"one: %count% strona|some: %count% strony"

is not an exact match for the ones that you highlight - from what I can see.

We have an [outstanding issue](https://github.com/mautic/mautic/issues/9606) with our release process whereby the language strings are not being updated and pushed to Transifex - I think that @alanhartless and @dennisameling were working on trying to get to the bottom of that particular issue.

**Comment by tomekkowalczyk** [comment]
@RCheesley a request to open a task, the problem is not solved.

**Comment by RCheesley** [comment]
I have just checked this in Mautic 4 (features branch) and after switching to Polish I am seeing the pagination working great, in Polish.

![screenshot-mautic4 ddev site-2021 06 24-20_55_47](https://user-images.githubusercontent.com/2930593/123324423-b661b280-d52e-11eb-9a90-d2848b20d959.png)

Closing this issue as it seems that it is resolved - maybe you need to pull down the translations / update your Mautic version?

**Comment by zaharovrd** [comment]
Have same error on Russian in Mautic 4.2.0
Russian language
Error not resolved
